apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d3j59f46p-go 
  janus-idp.io/tekton: d3j59f46p-go
  backstage.io/kubernetes-id: d3j59f46p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d3j59f46p-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml