apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: d3j59f46p-go-gitops
  description: This is GitOps manifest for d3j59f46p-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=d3j59f46p-go
    backstage.io/kubernetes-id: d3j59f46p-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: d3j59f46p-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:d3j59f46p-go
